version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  test:
    commands:
      - echo Run Unit Tests...
      - gradlew test
  build:
    commands:
      - echo Build started on `date`
      - gradlew clean build
      - sam build
      - echo Build completed on `date`
  package:
    commands:
      - echo Packaging the code...
      - sam package --s3-bucket pavel-shakhlovich-artifacts --output-template-file ./.aws-sam/build/template.yaml
artifacts:
  files:
    - .aws-sam/build/template.yaml