AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS SAM Lambda application.

Globals:
  Function:
    Runtime: java11
    MemorySize: 512
    Timeout: 20
    Layers:
      - Ref: MyLayer
    DeploymentPreference:
      Type: AllAtOnce
    AutoPublishAlias: live

Resources:
  MyLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: task-10-1-layer
      Description: Includes aws-java-sdk, aws-lambda-java-events, aws-lambda-java-core from Java SDK v.1
      ContentUri: s3://pavel-shakhlovich-artifacts/lambda-layer.zip
      CompatibleRuntimes:
        - java11
      RetentionPolicy: Delete

  NotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Java function that reads messages from SQS and sends to SNS
      CodeUri: build/distributions/aws-ci-cd-task-1.0-SNAPSHOT.zip
      Handler: com.epam.cloudx.pavelsh.awscicd.lambda.ImageProcessHandler
      FunctionName: Task-10-batch-notifier
      Role: arn:aws:iam::150063193970:role/LambdaSqsSnsRole
      PackageType: Zip
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /batch-notifier
            Method: post

  ApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Java function that simply returns input event
      CodeUri: build/distributions/aws-ci-cd-task-1.0-SNAPSHOT.zip
      Handler: com.epam.cloudx.pavelsh.awscicd.lambda.ApplicationHandler
      FunctionName: Task-10-ci-cd-test
      Policies: AWSLambdaBasicExecutionRole
      PackageType: Zip
